title: Mac Martine
author:
  name: Mac Martine
  handle: macmartine
url: http://macmartine.com
imagePath: /resources/images
permalink: /:categories/:title/
exclude: [vendor, Gemfile, Gemfile.lock]
timezone: America/Los Angeles
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: resources/_scss
  style: :compressed  

defaults:
  -
    scope:
      type: "posts"
    values:
      location: "Portland Or"
      layout: "post"
      category: "articles"
