- name: John Koenig
  title: Founder
  image: john-koenig.jpg
  company: Measureful, Warm Current, Swell Path
  url: http://warmcurrent.org
  quote: "Transforming an idea to a successful SaaS product proves to be a longer road than many entrpreneurs go into it expecting. Mac's experience and extreme passion for helping bootstrapping startups make his knowledge and insights an invaluable asset. Your business is sure to get a huge boost if you apply his tactics."

